### ISSUE TITLE
Http server not working

### ISSUE THREAD

**Issue by kdeklvadiya** [Hamielkuo/NodeMCU.HX711#1]
Hi thanks for the code but http server not starting at all, if I pit the ip add in Browser its show website has rejct to join.....please help, I am new to programing.......thanks in advance

**Comment by kdeklvadiya** [comment]
@Hamielkuo please help....
as and when i connect to server its show only "{\"msg\":\"ok\"}" nothing happen further

**Comment by Hamielkuo** [comment]
Sorry, too late to respond,
I did not touch your situation, but the following article seems useful to you, you can try。

http://randomnerdtutorials.com/esp8266-web-server/

**Comment by kdeklvadiya** [comment]
@hamielkuo

Thanks for the reply....I have gone through the issue and search around google and found there is an issue with HX711 library I.e. some yield function reset the esp8266......once again thanks for your code and replay...

**Comment by Hamielkuo** [comment]
^^,OK
